name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuos Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respoitory
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependecies
        run: npm install

      - name: Run tests
        run: npm test
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{secrets.EAS_EXPO_TOKEN}}
      
      - name: Build
        run: eas build --platform android --profile preview --non-interactive --no-wait
